# Generated by Django 4.2.1 on 2023-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(default='2023-06-05'),
            preserve_default=False,
        ),
    ]
